# -*- coding: utf-8 -*-
"""Consolidating all educational attainment 2010-2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKT_3HAbyZtYLeTFrsc1iPiR93xOjuqH
"""

import pandas as pd

# Step 1: Load both datasets
edu1 = pd.read_excel("/content/ACS_Education_2010_2014.xlsm")
edu2 = pd.read_excel("/content/ACS_Education_2015_2024.xlsx")

# Step 2: Stack them together
edu_final = pd.concat([edu1, edu2], ignore_index=True)

# Step 3: Sort (VERY important for panel data)
# Replace 'FIPS' if your county column has a different name
edu_final = edu_final.sort_values(by=["FIPS", "Year"])

# Step 4: Reset index
edu_final = edu_final.reset_index(drop=True)

# Step 5: Save final dataset
edu_final.to_excel("ACS_Education_2010_2024_FINAL.xlsx", index=False)

print("DONE!! Your education dataset is fully stacked 🎉")

edu_final['Year'].value_counts().sort_index()

set(edu1.columns) == set(edu2.columns)

edu_final.duplicated(subset=["FIPS", "Year"]).sum()

edu_final.columns