# -*- coding: utf-8 -*-
"""Fiddling Around with Senior Thesis Data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3_k3lYHB1Rh_EyXSxROOeJC_pTU9WKt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

!pip install linearmodels

from linearmodels.panel import PanelOLS

#Python can only read one sheet at a time
#I'm specifying that I want to read the second sheet from the excel file
ALLCOUNTIES = pd.read_excel("/content/CENSUS ALL COUNTIES.xlsm", sheet_name=1)

ALLCOUNTIES.columns

ALLCOUNTIES.info()

ruralurbancodes2013=pd.read_excel('/content/ruralurbancodes2013.xls')

ruralurbancodes2013.columns

racialcomposition=pd.read_excel('/content/Consolidated ACS Racial Composition.xlsm')

racialcomposition.columns

poverty=pd.read_excel('/content/Consolidated ACS Poverty.xlsm')

poverty.columns

medianhouseholdincome=pd.read_excel('/content/Consolidated ACS Median Household Income.xlsm')

medianhouseholdincome.columns

medianhomevalue=pd.read_excel('/content/Consolidated ACS Median Home Value.xlsm')

medianhomevalue.columns

educationalattainment=pd.read_excel('/content/Consolidated ACS Educational Attainment.xlsm')

educationalattainment.columns

age=pd.read_excel('/content/Consolidated ACS AGE DATA.xlsm')

age.columns

renter_owner=pd.read_excel('/content/Consolidated ACS % renter vs owner.xlsm')

renter_owner.columns

elderlycostburdenedhouseholds=pd.read_excel('/content/Consolidated ACS % Elderly Cost Burdened Data.xlsm')

elderlycostburdenedhouseholds.columns

import pandas as pd

years = pd.DataFrame({'year': range(2010, 2025)})

ALLCOUNTIES_panel = ALLCOUNTIES.merge(years, how='cross')

print(ALLCOUNTIES_panel.head())
print(ALLCOUNTIES_panel.shape)

ALLCOUNTIES_panel['treated'] = (
    (ALLCOUNTIES_panel['year'] >= ALLCOUNTIES_panel['joined_year'])
    & (ALLCOUNTIES_panel['joined_or_not'] == 1)
).astype(int)

print(ALLCOUNTIES_panel.columns.tolist())

#cleaning column names
ALLCOUNTIES_panel.columns = ALLCOUNTIES_panel.columns.str.strip()

#Renaming FIPS
ALLCOUNTIES_panel = ALLCOUNTIES_panel.rename(columns={
    '5 digit FIPS': 'FIPS'
})

ALLCOUNTIES_panel[['FIPS', 'year', 'joined_year', 'treated']].head(20)

print(poverty.columns.tolist())
print(poverty.head())

print(poverty.columns.tolist())

print(ALLCOUNTIES_panel[['FIPS', 'year']].dtypes)
print(poverty[['FIPS', 'Year']].dtypes)

#Convert FIPS to numeric
poverty['FIPS'] = pd.to_numeric(poverty['FIPS'], errors='coerce')

print(poverty['FIPS'].isna().sum())
print(poverty[['FIPS', 'Year']].head())

poverty[poverty['FIPS'].isna()][['GEO_ID', 'County_Name', 'State_Name', 'Year']].head(30)

poverty = poverty.dropna(subset=['FIPS']).copy()

print(poverty['FIPS'].isna().sum())

poverty['FIPS'] = poverty['FIPS'].astype(int)

print(poverty[['FIPS', 'Year']].head())
print(poverty.dtypes)

df = ALLCOUNTIES_panel.merge(
    poverty[['FIPS', 'Year', 'pct_below_poverty_poverty_pop']],
    left_on=['FIPS', 'year'],
    right_on=['FIPS', 'Year'],
    how='left'
)

print(df[['FIPS', 'year', 'pct_below_poverty_poverty_pop']].head(20))
print(df.shape)
print(df['pct_below_poverty_poverty_pop'].isna().sum())

poverty[poverty['FIPS'] == 12001][[
    'FIPS',
    'Year',
    'total_poverty_pop',
    'below_poverty_poverty_pop',
    'pct_below_poverty_poverty_pop'
]].head(15)

poverty['poverty_rate'] = (
    pd.to_numeric(poverty['below_poverty_poverty_pop'], errors='coerce') /
    pd.to_numeric(poverty['total_poverty_pop'], errors='coerce')
) * 100

poverty[poverty['FIPS'] == 12001][[
    'FIPS',
    'Year',
    'total_poverty_pop',
    'below_poverty_poverty_pop',
    'poverty_rate'
]].head(15)

df = ALLCOUNTIES_panel.merge(
    poverty[['FIPS', 'Year', 'poverty_rate']],
    left_on=['FIPS', 'year'],
    right_on=['FIPS', 'Year'],
    how='left'
)

print(df[['FIPS', 'year', 'poverty_rate']].head(20))
print(df.shape)
print(df['poverty_rate'].isna().sum())

df = df.drop(columns=['Year'])

print(df.columns)

#Moving onto medianhousholdincome data set
print(medianhouseholdincome.columns.tolist())
print(medianhouseholdincome.head())

print(medianhouseholdincome['median_hh_income'].dtype)

medianhouseholdincome['median_hh_income'] = pd.to_numeric(
    medianhouseholdincome['median_hh_income'],
    errors='coerce'
)

medianhouseholdincome['FIPS'] = pd.to_numeric(
    medianhouseholdincome['FIPS'],
    errors='coerce'
)

print(medianhouseholdincome['FIPS'].isna().sum())

medianhouseholdincome[medianhouseholdincome['FIPS'].isna()][
    ['GEO_ID', 'County_Name', 'State_Name', 'Year']
].head(40)

medianhouseholdincome = medianhouseholdincome.dropna(subset=['FIPS']).copy()

print(medianhouseholdincome['FIPS'].isna().sum())

medianhouseholdincome['FIPS'] = medianhouseholdincome['FIPS'].astype(int)

print(medianhouseholdincome[['FIPS', 'Year']].head())
print(medianhouseholdincome.dtypes)

df = df.merge(
    medianhouseholdincome[['FIPS', 'Year', 'median_hh_income']],
    left_on=['FIPS', 'year'],
    right_on=['FIPS', 'Year'],
    how='left'
)

print(df[['FIPS', 'year', 'median_hh_income']].head(20))
print(df.shape)
print(df['median_hh_income'].isna().sum())

medianhouseholdincome[medianhouseholdincome['FIPS'] == 12001][[
    'FIPS',
    'Year',
    'median_hh_income'
]].head(15)

print(medianhouseholdincome.columns.tolist())













































































