# -*- coding: utf-8 -*-
"""fiddling with merging senior thesis data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ny8dHXWx1zeo9BoGSToGgTF5tSuI7pK3
"""

import pandas as pd

census = pd.read_excel("/content/CENSUS_ALL_COUNTIES_expanded_2010_2024.xlsx")
acs = pd.read_excel("/content/acs_rural_merged_only.xlsx")

# === Clean column names just in case ===
census.columns = census.columns.str.strip()
acs.columns = acs.columns.str.strip()

# === Make sure merge keys are named consistently ===
# Only needed if your columns already are exactly "FIPS" and "Year", but harmless
census = census.rename(columns={"fips": "FIPS", "year": "Year"})
acs = acs.rename(columns={"fips": "FIPS", "year": "Year"})

# === Optional: make sure FIPS and Year have same type in both sheets ===
census["FIPS"] = census["FIPS"].astype(str).str.zfill(5)
acs["FIPS"] = acs["FIPS"].astype(str).str.zfill(5)

census["Year"] = pd.to_numeric(census["Year"], errors="coerce")
acs["Year"] = pd.to_numeric(acs["Year"], errors="coerce")

# === Find overlapping columns other than merge keys ===
merge_keys = ["FIPS", "Year"]
duplicate_cols = [col for col in census.columns if col in acs.columns and col not in merge_keys]

print("Duplicate columns being dropped from census sheet:")
print(duplicate_cols)

# === Drop duplicate columns from census before merge ===
census = census.drop(columns=duplicate_cols)

# === Merge ===
merged = pd.merge(
    acs,
    census,
    on=["FIPS", "Year"],
    how="left"
)

# === Save result ===
merged.to_excel("merged_acs_census.xlsx", index=False)

print("Done! File saved as 'merged_acs_census.xlsx'")
print(merged.head())