# -*- coding: utf-8 -*-
"""Fidgeting with census data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJuDCAHTAWJCOrnGq3OyMdlFBvqNuuNp
"""

import pandas as pd
import numpy as np

# === STEP 1: Load your census file ===
# Change the file name/path if needed
df = pd.read_excel("/content/CENSUS ALL COUNTIES.xlsm")

# === STEP 2: Create the list of years ===
years = list(range(2010, 2025))   # 2010 through 2024

# === STEP 3: Repeat each county row for every year ===
df_expanded = df.loc[df.index.repeat(len(years))].copy()

# === STEP 4: Add the Year column ===
df_expanded["Year"] = np.tile(years, len(df))

# === STEP 5: Optional - reorder columns so Year is near the front ===
cols = df_expanded.columns.tolist()

# Put Year as the second column (after the first existing column)
if "Year" in cols:
    cols.insert(1, cols.pop(cols.index("Year")))
    df_expanded = df_expanded[cols]

# === STEP 6: Save the expanded file ===
df_expanded.to_excel("CENSUS_ALL_COUNTIES_expanded_2010_2024.xlsx", index=False)

print("Done! Expanded file saved as 'CENSUS_ALL_COUNTIES_expanded_2010_2024.xlsx'")
print(df_expanded.head(20))