# -*- coding: utf-8 -*-
"""Fixing stuff from senior thesis tables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1MELDzRNpoxrg0fp0sv2OpoY5CAI6nT
"""

import pandas as pd

df = pd.read_excel('/content/HOLY GRAIL MASS INFO DOC.xlsx')

df['joined'].describe()

df['joined'].unique()

df.columns

vars_needed = [
    'pct_hh65plus_cost_30plus_pct',
    'static_joined_or_not(not taking into account year)',
    'poverty_rate',
    '65plus_poverty_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_white',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

summary_table = df[vars_needed].describe().T
summary_table = summary_table[['mean', 'std', 'min', '25%', '50%', '75%', 'max']]

summary_table

summary_table.index = [
    '% 65+ Cost Burdened',
    'Ever Joined',
    'Poverty Rate',
    '65+ Poverty Rate',
    'Median Household Income',
    '% Bachelor’s Degree or Higher',
    'Median Home Value',
    '% Renter',
    'Total Population',
    '% Age 65+',
    '% White',
    '% Black',
    '% Hispanic',
    '% Asian',
    '% Multiracial',
    'Urban-Rural (RUCC)'
]

summary_table

df['pop_total_thousands'] = df['pop_total'] / 1000
df['median_home_value_thousands'] = df['median_home_value'] / 1000
df['median_household_income_thousands'] = df['median_household_income'] / 1000

vars_needed = [
    'pct_hh65plus_cost_30plus_pct',
    'static_joined_or_not(not taking into account year)',
    'poverty_rate',
    '65plus_poverty_rate',
    'median_household_income_thousands',
    'pct_bachelors_or_higher',
    'median_home_value_thousands',
    'percent_renter',
    'pop_total_thousands',
    'pct_65plus',
    'pct_white',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

summary_table = df[vars_needed].describe().T
summary_table = summary_table[['mean', 'std', 'min', '25%', '50%', '75%', 'max']]

summary_table.index = [
    '% 65+ Cost Burdened',
    'Ever Joined',
    'Poverty Rate',
    '65+ Poverty Rate',
    'Median Household Income (Thousands)',
    '% Bachelor’s Degree or Higher',
    'Median Home Value (Thousands)',
    '% Renter',
    'Total Population (Thousands)',
    '% Age 65+',
    '% White',
    '% Black',
    '% Hispanic',
    '% Asian',
    '% Multiracial',
    'Urban-Rural (RUCC)'
]

summary_table

summary_table = summary_table.round(2)
summary_table

df['pop_total_thousands'] = df['pop_total'] / 1000
df['median_home_value_thousands'] = df['median_home_value'] / 1000
df['median_household_income_thousands'] = df['median_household_income'] / 1000

vars_compare = [
    'pct_hh65plus_cost_30plus_pct',
    'poverty_rate',
    '65plus_poverty_rate',
    'median_household_income_thousands',
    'pct_bachelors_or_higher',
    'median_home_value_thousands',
    'percent_renter',
    'pop_total_thousands',
    'pct_65plus',
    'pct_white',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

group_means = df.groupby('static_joined_or_not(not taking into account year)')[vars_compare].mean().T
group_means.columns = ['Never Joined', 'Ever Joined']

group_means['Difference (Ever - Never)'] = (
    group_means['Ever Joined'] - group_means['Never Joined']
)

import numpy as np

std_diff = []

for var in vars_compare:
    group0 = df[df['joined'] == 0][var]
    group1 = df[df['joined'] == 1][var]

    mean_diff = group1.mean() - group0.mean()

    pooled_std = np.sqrt((group1.std()**2 + group0.std()**2) / 2)

    std_diff.append(mean_diff / pooled_std)

group_means['Std. Diff.'] = std_diff

group_means.index = [
    '% 65+ Cost Burdened',
    'Poverty Rate',
    '65+ Poverty Rate',
    'Median Household Income (Thousands)',
    '% Bachelor’s Degree or Higher',
    'Median Home Value (Thousands)',
    '% Renter',
    'Total Population (Thousands)',
    '% Age 65+',
    '% White',
    '% Black',
    '% Hispanic',
    '% Asian',
    '% Multiracial',
    'Urban-Rural (RUCC)'
]

group_means = group_means.round(2)
group_means

df_county_avg = df.groupby('FIPS')['pop_total'].mean().reset_index()

large_counties = df_county_avg[df_county_avg['pop_total'] >= 100000]['FIPS']

df_pop100_strict = df[df['FIPS'].isin(large_counties)].copy()

df_pop100_strict.groupby('static_joined_or_not(not taking into account year)')['FIPS'].nunique()

counts = df_pop100_strict.groupby('static_joined_or_not(not taking into account year)')['FIPS'].nunique()

print(f"Never Joined Counties: {counts.get(0, 0)}")
print(f"Ever Joined Counties: {counts.get(1, 0)}")

df_pop100_strict[['FIPS', 'static_joined_or_not(not taking into account year)']].drop_duplicates().shape

df_pop100_strict['FIPS'].nunique()

import pandas as pd
import matplotlib.pyplot as plt

# Make a copy
df_plot = df.copy()

# Optional: make sure Year is numeric
df_plot['Year'] = pd.to_numeric(df_plot['Year'], errors='coerce')

# Main variables
group_var = 'static_joined_or_not(not taking into account year)'
outcome = 'pct_65plus'

# Drop missing values
df_plot = df_plot.dropna(subset=['Year', group_var, outcome])

# Aggregate by year and ever-joined status
trend = (
    df_plot
    .groupby(['Year', group_var])[outcome]
    .mean()
    .reset_index()
)

# Pivot so each group becomes a line
trend_pivot = trend.pivot(index='Year', columns=group_var, values=outcome)

# Plot
plt.figure(figsize=(10, 6))

for col in trend_pivot.columns:
    label = 'Ever Joined AARP' if col == 1 else 'Never Joined AARP'
    plt.plot(trend_pivot.index, trend_pivot[col], marker='o', label=label)

plt.title('% 65+ Population Over Time: AARP Joiner vs Non-Joiner Counties')
plt.xlabel('Year')
plt.ylabel('% 65+ Population')
plt.legend()
plt.grid(True)
plt.show()

df.groupby('joined')['pct_65plus'].mean()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Select variables
vars_of_interest = [
    '65plus_poverty_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

# Subset dataframe
df_subset = df[vars_of_interest]

# Compute correlation matrix
corr_matrix = df_subset.corr()

# Print it (table form)
print(corr_matrix)

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.5)

plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

# Use same variables as regression (IMPORTANT)
X = df[[
    '65plus_poverty_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]].dropna()

# Add constant
import statsmodels.api as sm
X = sm.add_constant(X)

# Compute VIF
vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

print(vif_data)



