# -*- coding: utf-8 -*-
"""merging poverty data with holy grail all data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ViBct-za4NXKKnEh3v18C4DzR0iS3adQ
"""

import pandas as pd

# Step 1: Load both datasets
holy = pd.read_excel("/content/HOLY GRAIL MASS INFO DOC.xlsx")
poverty = pd.read_excel("/content/Consolidated ACS Poverty Individual Years.xlsm")  # or your file name

# Step 2: Clean column names (important!!)
holy.columns = holy.columns.str.strip()
poverty.columns = poverty.columns.str.strip()

# Step 3: Make sure FIPS formats match
holy["FIPS"] = holy["FIPS"].astype(str).str.zfill(5)
poverty["FIPS"] = poverty["GEO_ID"].str[-5:]  # extract FIPS from GEO_ID

# Step 4: Merge (LEFT JOIN)
merged = pd.merge(
    holy,
    poverty[["FIPS", "Year", "poverty_rate", "65plus_poverty_rate"]],
    on=["FIPS", "Year"],
    how="left"
)

# Step 5: Preview
print(merged.head())

print(merged[["Year", "poverty_rate"]].groupby("Year").count())

merged.to_csv("HOLY_GRAIL_WITH_POVERTY.csv", index=False)





