# -*- coding: utf-8 -*-
"""merging poverty data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDhCj9n4me3EIb6AKzi_3DxP8wPzcKFI
"""

import pandas as pd
import glob
import re

files = glob.glob("ACSST5Y*.S1701-Data.csv")

dfs = []

for file in files:
    print(f"Processing: {file}")

    year = int(re.search(r'ACSST5Y(\d{4})', file).group(1))

    # Read file
    df = pd.read_csv(file, low_memory=False)

    # Clean column names
    df.columns = df.columns.str.strip()

    # 🔍 Check if required columns exist
    required_cols = ["GEO_ID", "NAME", "S1701_C03_001E", "S1701_C03_010E"]

    missing = [col for col in required_cols if col not in df.columns]

    if missing:
        print(f"❌ Skipping {file} — missing columns: {missing}")
        continue  # skip bad file instead of crashing

    # Keep only needed columns
    df = df[required_cols].copy()

    # Add year
    df["Year"] = year

    dfs.append(df)

# Combine
final_df = pd.concat(dfs, ignore_index=True)

# Rename
final_df = final_df.rename(columns={
    "NAME": "County_Name",
    "S1701_C03_001E": "poverty_rate",
    "S1701_C03_010E": "elderly_poverty_rate"
})

print(final_df.head())

final_df.to_csv("poverty_stacked_2012_2014.csv", index=False)

























