# -*- coding: utf-8 -*-
"""merging rural urban with mass info holy grail doc .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YUy-cUn3C2-NTKQ9s6uupMRS-82_f85
"""

import pandas as pd

# Load your files (replace with your actual file names if needed)
holy = pd.read_excel("/content/HOLY GRAIL MASS INFO DOC.xlsx")
rucc = pd.read_excel("/content/rural_urban_expanded.xlsx")

# Clean column names just in case
holy.columns = holy.columns.str.strip()
rucc.columns = rucc.columns.str.strip()

# Clean FIPS
holy["FIPS"] = holy["FIPS"].astype(str).str.strip().str.zfill(5)
rucc["FIPS"] = rucc["FIPS"].astype(str).str.strip().str.zfill(5)

# Clean Year
holy["Year"] = pd.to_numeric(holy["Year"], errors="coerce").astype("Int64")
rucc["Year"] = pd.to_numeric(rucc["Year"], errors="coerce").astype("Int64")

# Keep only needed columns
rucc_subset = rucc[["FIPS", "Year", "RUCC_2013"]].drop_duplicates()

# Merge
merged = holy.merge(rucc_subset, on=["FIPS", "Year"], how="left")

# Check missing values
print("Missing RUCC_2013 values:", merged["RUCC_2013"].isna().sum())

# Save
merged.to_excel("HOLY_GRAIL_with_RUCC.xlsx", index=False)

merged["RUCC_2013"].isna().sum()