# -*- coding: utf-8 -*-
"""Parsing through ruralurbancodes data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbgC2imXm0Xmd80Bf5bACDMlHeg9BETs
"""

import pandas as pd

# Step 1: Load your dataset
df = pd.read_excel("/content/ruralurbancodes2013.xls")

# Step 2: Create list of years
years = list(range(2010, 2025))  # 2010–2024

# Step 3: Repeat each row for each year
df_expanded = df.loc[df.index.repeat(len(years))].copy()

# Step 4: Assign year column
df_expanded['year'] = years * len(df)

# Step 5: Reset index (cleaner)
df_expanded = df_expanded.reset_index(drop=True)

# Step 6: Save it
df_expanded.to_excel("rural_urban_expanded.xlsx", index=False)

df_expanded.head(20)