# -*- coding: utf-8 -*-
"""running regressions for senior thesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwIlkbYiRfXoY8aNAClmoHcbG96XdUoh
"""

import pandas as pd

df = pd.read_excel("/content/HOLY GRAIL MASS INFO DOC.xlsx")

df.head()

df.shape

df.dtypes

df[['FIPS', 'Year', 'joined', 'join_year', 'years_since_joined']].head()

df['joined'] = df['joined'].astype(int)
df['Year'] = df['Year'].astype(int)

df["FIPS"] = df["FIPS"].astype(str).str.zfill(5)

#simple regression
#dependent variable is hh65plus_cost_30plus_pct
import statsmodels.formula.api as smf

model1 = smf.ols(
    'hh65plus_cost_30plus_pct ~ joined',
    data=df
).fit()

print(model1.summary())

#Adding County + Year fixed effects
#C(FIPS) → controls for each county
#C(Year) → controls for each year
model2 = smf.ols(
    'hh65plus_cost_30plus_pct ~ joined + C(FIPS) + C(Year)',
    data=df
).fit()

print(model2.summary())

#Adding median_

























