# -*- coding: utf-8 -*-
"""Senior thesis paper tables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLLQ42-NoD58gX6uLellZlh6nrZCYqLV
"""

import pandas as pd
holygrail=pd.read_excel('/content/HOLY GRAIL MASS INFO DOC.xlsx')

holygrail.columns

import pandas as pd
import numpy as np

# Select variables for summary statistics table
summary_vars = [
    'pct_hh65plus_cost_30plus_pct',   # dependent variable
    'joined',                         # treatment variable
    'poverty_rate',
    '65plus_poverty_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_white',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial'
]

# Keep only variables that actually exist in the dataframe
summary_vars = [col for col in summary_vars if col in holygrail.columns]

# Create summary statistics table
summary_table = holygrail[summary_vars].describe().T

# Keep only the standard columns used in econ papers
summary_table = summary_table[['count', 'mean', 'std', 'min', 'max']]

# Rename columns for nicer presentation
summary_table = summary_table.rename(columns={
    'count': 'N',
    'mean': 'Mean',
    'std': 'Std. Dev.',
    'min': 'Min',
    'max': 'Max'
})

# Round values
summary_table = summary_table.round(3)

# Display table
summary_table

import pandas as pd
import numpy as np

# Variables to include
summary_vars = [
    'pct_hh65plus_cost_30plus_pct',
    'joined',
    'poverty_rate',
    '65plus_poverty_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_white',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'   # ✅ added here
]

# Make a copy
df = holygrail[summary_vars].copy()

# Variables stored as proportions → convert to %
proportion_vars = [
    'pct_hh65plus_cost_30plus_pct',
    'joined',
    'pct_bachelors_or_higher',
    'percent_renter',
    'pct_65plus',
    'pct_white',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial'
]

df[proportion_vars] = df[proportion_vars] * 100

# Create summary stats
summary_table = df.describe().T[['count', 'mean', 'std', 'min', 'max']]
summary_table.columns = ['N', 'Mean', 'Std. Dev.', 'Min', 'Max']

# Pretty names
pretty_names = {
    'pct_hh65plus_cost_30plus_pct': '% 65+ Households Cost Burdened',
    'joined': 'Joined AARP Network (%)',
    'poverty_rate': 'Poverty Rate',
    '65plus_poverty_rate': '65+ Poverty Rate',
    'median_household_income': 'Median Household Income',
    'pct_bachelors_or_higher': '% Bachelor’s Degree or Higher',
    'median_home_value': 'Median Home Value',
    'percent_renter': '% Renter-Occupied',
    'pop_total': 'Total Population',
    'pct_65plus': '% Population Age 65+',
    'pct_white': '% White',
    'pct_black': '% Black',
    'pct_hispanic': '% Hispanic',
    'pct_asian': '% Asian',
    'pct_multiracial': '% Multiracial',
    'urban_rural_classification': 'Urban–Rural (RUCC)'
}

summary_table.index = [pretty_names.get(v, v) for v in summary_table.index]

# Round
summary_table = summary_table.round(2)

# Display nicely
summary_table.style.format({
    'N': '{:,.0f}',
    'Mean': '{:,.2f}',
    'Std. Dev.': '{:,.2f}',
    'Min': '{:,.2f}',
    'Max': '{:,.2f}'
})

"""# Comparison tables of counties that joined vs counties that never joined"""

holygrail = holygrail.rename(columns={
    'static_joined_or_not(not taking into account year)': 'ever_joined'
})

import pandas as pd

# Variables you want
vars_list = [
    'pct_hh65plus_cost_30plus_pct',
    'poverty_rate',
    '65plus_poverty_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_white',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

# Copy data
df = holygrail[vars_list + ['ever_joined']].copy()

# Convert proportions to percentages (for readability)
proportion_vars = [
    'pct_hh65plus_cost_30plus_pct',
    'pct_bachelors_or_higher',
    'percent_renter',
    'pct_65plus',
    'pct_white',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial'
]

df[proportion_vars] = df[proportion_vars] * 100

# Group means
group_means = df.groupby('ever_joined').mean()

# Rename groups
group_means.index = ['Never Joined', 'Ever Joined']

# Transpose for nicer format
comparison_table = group_means.T

comparison_table.round(2)

comparison_table['Difference (Ever - Never)'] = (
    comparison_table['Ever Joined'] - comparison_table['Never Joined']
)

comparison_table = comparison_table.round(2)

comparison_table

pretty_names = {
    'pct_hh65plus_cost_30plus_pct': '% 65+ Cost Burdened',
    'poverty_rate': 'Poverty Rate',
    '65plus_poverty_rate': '65+ Poverty Rate',
    'median_household_income': 'Median Household Income',
    'pct_bachelors_or_higher': '% Bachelor’s or Higher',
    'median_home_value': 'Median Home Value',
    'percent_renter': '% Renter',
    'pop_total': 'Total Population',
    'pct_65plus': '% Age 65+',
    'pct_white': '% White',
    'pct_black': '% Black',
    'pct_hispanic': '% Hispanic',
    'pct_asian': '% Asian',
    'pct_multiracial': '% Multiracial',
    'urban_rural_classification': 'Urban–Rural (RUCC)'
}

comparison_table.index = [pretty_names.get(v, v) for v in comparison_table.index]

comparison_table

import numpy as np

# Split groups
group0 = df[df['ever_joined'] == 0]
group1 = df[df['ever_joined'] == 1]

# Compute pooled standard deviation
pooled_sd = np.sqrt(
    (group0[vars_list].var() + group1[vars_list].var()) / 2
)

# Compute standardized difference
std_diff = (group1[vars_list].mean() - group0[vars_list].mean()) / pooled_sd

# Add to your table
comparison_table['Std. Diff.'] = std_diff.values

# Round
comparison_table = comparison_table.round(2)

comparison_table

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

# Make a copy so you don't overwrite your original
df = holygrail.copy()

# Optional: rename awkward column names if needed
df = df.rename(columns={
    'static_joined_or_not(not taking into account year)': 'ever_joined'
})

# Make sure FIPS is treated as a string for fixed effects
df['FIPS'] = df['FIPS'].astype(str)

# Variables for the model
dependent_var = 'pct_hh65plus_cost_30plus_pct'

treatment_var = 'joined'

controls = [
    'poverty_rate',
    '65plus_poverty_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

# Keep only needed columns for regression
regression_vars = [dependent_var, treatment_var, 'FIPS', 'Year'] + controls
reg_df = df[regression_vars].copy()

# Drop rows with missing values in any regression variable
reg_df = reg_df.dropna()

print(reg_df.shape)
reg_df.head()

df = df.rename(columns={
    '65plus_poverty_rate': 'pov65plus_rate'
})

controls = [
    'poverty_rate',
    'pov65plus_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

model1 = smf.ols(
    f"{dependent_var} ~ {treatment_var}",
    data=reg_df
).fit(cov_type='cluster', cov_kwds={'groups': reg_df['FIPS']})

print(model1.summary())

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

# Start fresh from holygrail
df = holygrail.copy()

# Rename awkward columns FIRST
df = df.rename(columns={
    'static_joined_or_not(not taking into account year)': 'ever_joined',
    '65plus_poverty_rate': 'pov65plus_rate'
})

# Make sure FIPS is a string
df['FIPS'] = df['FIPS'].astype(str)

# Define variables
dependent_var = 'pct_hh65plus_cost_30plus_pct'
treatment_var = 'joined'

controls = [
    'poverty_rate',
    'pov65plus_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

# Build regression dataframe AFTER renaming
regression_vars = [dependent_var, treatment_var, 'FIPS', 'Year'] + controls
reg_df = df[regression_vars].copy()

# Drop missing values
reg_df = reg_df.dropna()

# Check columns to confirm
print(reg_df.columns.tolist())

controls_formula = " + ".join(controls)

model2 = smf.ols(
    f"{dependent_var} ~ {treatment_var} + {controls_formula}",
    data=reg_df
).fit(cov_type='cluster', cov_kwds={'groups': reg_df['FIPS']})

print(model2.summary())

model3 = smf.ols(
    f"{dependent_var} ~ {treatment_var} + {controls_formula} + C(FIPS) + C(Year)",
    data=reg_df
).fit(cov_type='cluster', cov_kwds={'groups': reg_df['FIPS']})

print(model3.summary())

def extract_results(model, model_name):
    results = pd.DataFrame({
        f'{model_name} Coef.': model.params,
        f'{model_name} Std. Err.': model.bse,
        f'{model_name} t-stat': model.tvalues,
        f'{model_name} p-value': model.pvalues
    })
    return results

table1 = extract_results(model1, 'Model 1')
table2 = extract_results(model2, 'Model 2')
table3 = extract_results(model3, 'Model 3')

results_table = pd.concat([table1, table2, table3], axis=1)

# Round for readability
results_table = results_table.round(4)

results_table.head(20)

main_vars = [treatment_var] + controls

main_results_table = results_table.loc[results_table.index.intersection(main_vars)].copy()

main_results_table

model_summary = pd.DataFrame({
    'Model': ['Model 1', 'Model 2', 'Model 3'],
    'Observations': [int(model1.nobs), int(model2.nobs), int(model3.nobs)],
    'R-squared': [model1.rsquared, model2.rsquared, model3.rsquared],
    'Adj. R-squared': [model1.rsquared_adj, model2.rsquared_adj, model3.rsquared_adj],
    'County FE': ['No', 'No', 'Yes'],
    'Year FE': ['No', 'No', 'Yes'],
    'Clustered SE by County': ['Yes', 'Yes', 'Yes']
})

model_summary = model_summary.round(4)
model_summary

"""# Next using "year_since_joined" variable--- kinda event study situation"""

# Copy data
event_df = df.copy()

# Keep only needed columns
event_vars = [dependent_var, 'years_since_joined', 'FIPS', 'Year'] + controls
event_df = event_df[event_vars].copy()

# Drop missing
event_df = event_df.dropna()

# Optional: cap extreme values (VERY recommended)
event_df['event_time'] = event_df['years_since_joined']

# Cap to avoid sparse bins (e.g., beyond +/-5)
event_df.loc[event_df['event_time'] <= -5, 'event_time'] = -5
event_df.loc[event_df['event_time'] >= 5, 'event_time'] = 5

model_event = smf.ols(
    f"{dependent_var} ~ C(event_time, Treatment(reference=-1)) + {controls_formula} + C(FIPS) + C(Year)",
    data=event_df
).fit(cov_type='cluster', cov_kwds={'groups': event_df['FIPS']})

print(model_event.summary())

event_coefs = model_event.params.filter(like='C(event_time)')
event_se = model_event.bse.filter(like='C(event_time)')

event_table = pd.DataFrame({
    'Coefficient': event_coefs,
    'Std. Err.': event_se
})

event_table = event_table.reset_index()
event_table.columns = ['Event Time', 'Coefficient', 'Std. Err.']

# Clean labels
event_table['Event Time'] = event_table['Event Time'].str.extract(r'\[T\.(.*)\]').astype(float)

event_table = event_table.sort_values('Event Time')

event_table

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.errorbar(
    event_table['Event Time'],
    event_table['Coefficient'],
    yerr=1.96 * event_table['Std. Err.'],
    fmt='o'
)

plt.axhline(0)
plt.axvline(0, linestyle='--')

plt.xlabel('Years Since Joining')
plt.ylabel('Effect on % 65+ Cost Burdened')
plt.title('Event Study: Impact of AARP Network Participation')

plt.show()

print(event_df.shape)
event_df['years_since_joined'].describe()
event_df['years_since_joined'].value_counts().sort_index()

df[['join_year', 'Year', 'years_since_joined']].head(10)

print(df['join_year'].notna().sum())
print(df['years_since_joined'].notna().sum())

df[df['join_year'].notna()][['FIPS', 'County_Name', 'Year', 'join_year', 'years_since_joined']].head(20)

df = holygrail.copy()

# rename if needed
df = df.rename(columns={
    '65plus_poverty_rate': 'pov65plus_rate',
    'static_joined_or_not(not taking into account year)': 'ever_joined'
})

# make sure numeric
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df['join_year'] = pd.to_numeric(df['join_year'], errors='coerce')

# rebuild years_since_joined
df['years_since_joined'] = df['Year'] - df['join_year']

# never-treated counties should stay missing
df.loc[df['join_year'].isna(), 'years_since_joined'] = np.nan

print(df[['Year', 'join_year', 'years_since_joined']].head(10))
print(df['years_since_joined'].describe())
print(df['years_since_joined'].value_counts().sort_index())

event_df = df.copy()

controls = [
    'poverty_rate',
    'pov65plus_rate',
    'median_household_income',
    'pct_bachelors_or_higher',
    'median_home_value',
    'percent_renter',
    'pop_total',
    'pct_65plus',
    'pct_black',
    'pct_hispanic',
    'pct_asian',
    'pct_multiracial',
    'urban_rural_classification'
]

dependent_var = 'pct_hh65plus_cost_30plus_pct'
controls_formula = " + ".join(controls)

# keep only rows with actual event time
event_df = event_df.dropna(subset=[dependent_var, 'years_since_joined'] + controls + ['FIPS', 'Year'])

# cap event time to avoid sparse tails
event_df['event_time'] = event_df['years_since_joined']
event_df.loc[event_df['event_time'] <= -5, 'event_time'] = -5
event_df.loc[event_df['event_time'] >= 5, 'event_time'] = 5

print(event_df['event_time'].value_counts().sort_index())

model_event = smf.ols(
    f"{dependent_var} ~ C(event_time, Treatment(reference=-1)) + {controls_formula} + C(FIPS) + C(Year)",
    data=event_df
).fit(cov_type='cluster', cov_kwds={'groups': event_df['FIPS']})

print(model_event.summary())

event_coefs = model_event.params.filter(like='C(event_time)')
event_se = model_event.bse.filter(like='C(event_time)')

event_table = pd.DataFrame({
    'Coefficient': event_coefs,
    'Std. Err.': event_se
}).reset_index()

event_table.columns = ['Event Time', 'Coefficient', 'Std. Err.']
event_table['Event Time'] = event_table['Event Time'].str.extract(r'T\.([-\d\.]+)').astype(float)
event_table = event_table.sort_values('Event Time')

event_table

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.errorbar(
    event_table['Event Time'],
    event_table['Coefficient'],
    yerr=1.96 * event_table['Std. Err.'],
    fmt='o'
)
plt.axhline(0)
plt.axvline(0, linestyle='--')
plt.xlabel('Years Since Joining')
plt.ylabel('Effect on % 65+ Cost Burdened')
plt.title('Semi-Event Study')
plt.show()

"""# Only keeping pop total greater than 100,000"""

# Start from your clean regression dataframe
df_large = reg_df.copy()

# Keep only counties with population >= 100,000
df_large = df_large[df_large['pop_total'] >= 100000]

print(df_large.shape)

model1_large = smf.ols(
    f"{dependent_var} ~ {treatment_var}",
    data=df_large
).fit(cov_type='cluster', cov_kwds={'groups': df_large['FIPS']})

model2_large = smf.ols(
    f"{dependent_var} ~ {treatment_var} + {controls_formula}",
    data=df_large
).fit(cov_type='cluster', cov_kwds={'groups': df_large['FIPS']})

model3_large = smf.ols(
    f"{dependent_var} ~ {treatment_var} + {controls_formula} + C(FIPS) + C(Year)",
    data=df_large
).fit(cov_type='cluster', cov_kwds={'groups': df_large['FIPS']})

def extract_results(model, name):
    return pd.DataFrame({
        f'{name} Coef.': model.params,
        f'{name} Std. Err.': model.bse,
        f'{name} t-stat': model.tvalues,
        f'{name} p-value': model.pvalues
    })

table_large = pd.concat([
    extract_results(model1_large, 'Model 1'),
    extract_results(model2_large, 'Model 2'),
    extract_results(model3_large, 'Model 3')
], axis=1)

table_large = table_large.round(4)

table_large.loc[['joined']]

import matplotlib.pyplot as plt
import numpy as np

models = ['Model 1', 'Model 2', 'Model 3']
coefs = [
    model1.params['joined'],
    model2.params['joined'],
    model3.params['joined']
]

ses = [
    model1.bse['joined'],
    model2.bse['joined'],
    model3.bse['joined']
]

plt.figure(figsize=(6,4))

plt.errorbar(models, coefs, yerr=[1.96*s for s in ses], fmt='o')

plt.axhline(0, linestyle='--')
plt.title('Effect of AARP Participation Across Models')
plt.ylabel('Coefficient on Joined')

plt.show()



























