# -*- coding: utf-8 -*-
"""Stacking Age Data 2017-2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbhtLIY8jTDE_CFBxfyi8PRZxvcD9tZL
"""

import pandas as pd
import glob
import re

# Step 1: Get all files for 2017–2024
files = sorted(glob.glob("ACSST5Y20*.S0101-Data.csv"))

# Filter ONLY 2017–2024
files = [f for f in files if re.search(r'20(1[7-9]|2[0-4])', f)]

# Step 2: Create empty list
df_list = []

# Step 3: Loop through each file
for file in files:

    # Extract year from filename
    year = re.search(r'(\d{4})', file).group(1)

    # Read file
    df = pd.read_csv(file)

    # Add Year column
    df['Year'] = int(year)

    # Append
    df_list.append(df)

# Step 4: Stack
combined_df_2 = pd.concat(df_list, ignore_index=True)

# Step 5: Save to Excel
combined_df_2.to_excel("ACS_2017_2024_stacked.xlsx", index=False)

print("Done! File saved as ACS_2017_2024_stacked.xlsx")