# -*- coding: utf-8 -*-
"""Stacking educational attainment 2025-2024 data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1olLlxUlbd1Je8tP3g8r4aOyQV0tMK7cC
"""

import pandas as pd
import glob
import re

# Step 1: Get all S1501 files
files = sorted(glob.glob("ACSST5Y20*.S1501-Data.csv"))

# Step 2: Filter ONLY 2015–2024
files = [f for f in files if re.search(r'20(1[5-9]|2[0-4])', f)]

# Step 3: Create list to store dataframes
df_list = []

# Step 4: Loop through each file
for file in files:

    # Extract year from filename
    year = re.search(r'(\d{4})', file).group(1)

    # Read file
    df = pd.read_csv(file)

    # Add Year column
    df['Year'] = int(year)

    # Append to list
    df_list.append(df)

# Step 5: Stack all dataframes
edu_2015_2024 = pd.concat(df_list, ignore_index=True)

# Step 6: Save to Excel
edu_2015_2024.to_excel("ACS_Education_2015_2024.xlsx", index=False)

print("Done! Education dataset (2015–2024) saved 🎉")