# -*- coding: utf-8 -*-
"""Stacking Age Data 2010-2016.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IyWokELwhroNDgXhWxOKzrtmUEocpQO
"""

import pandas as pd
import glob
import re

# Step 1: Get all files for 2010–2016
files = sorted(glob.glob("ACSST5Y201*.S0101-Data.csv"))

# Optional: filter only 2010–2016 explicitly (safer)
files = [f for f in files if re.search(r'201[0-6]', f)]

# Step 2: Create empty list to store dataframes
df_list = []

# Step 3: Loop through each file
for file in files:

    # Extract year from filename (e.g., 2010)
    year = re.search(r'(\d{4})', file).group(1)

    # Read file
    df = pd.read_csv(file)

    # Add Year column
    df['Year'] = int(year)

    # Append to list
    df_list.append(df)

# Step 4: Stack all dataframes
combined_df = pd.concat(df_list, ignore_index=True)

# Step 5: Save to Excel
combined_df.to_excel("ACS_2010_2016_stacked.xlsx", index=False)

print("Done! File saved as ACS_2010_2016_stacked.xlsx")