# -*- coding: utf-8 -*-
"""Stacking Consolidated 2010-2924 age ACS DATA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ViyZ-g0nvh9uQoxxsprl9NUtpAZCOlr
"""

import pandas as pd

# Step 1: Load both datasets
df1 = pd.read_excel("/content/ACS_2010_2016_stacked.xlsm")
df2 = pd.read_excel("/content/ACS_2017_2024_stacked.xlsm")

# Step 2: Stack them together
final_df = pd.concat([df1, df2], ignore_index=True)

# Step 3: Sort by county + year (VERY important for panel data)
# Replace 'FIPS' with your actual county identifier column name if different
final_df = final_df.sort_values(by=["FIPS", "Year"])

# Step 4: Reset index
final_df = final_df.reset_index(drop=True)

# Step 5: Save final dataset
final_df.to_excel("ACS_2010_2024_FINAL.xlsx", index=False)

print("DONE!! Your full 2010–2024 dataset is ready 🎉")

final_df.duplicated(subset=["FIPS", "Year"]).sum()