# -*- coding: utf-8 -*-
"""Stacking Educational Attainment 2010-2014 data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0MgtWd3lwqOjaXGRmzZ52T51OmSjmKh
"""

import pandas as pd
import glob
import re

# Step 1: Get all S1501 files
files = sorted(glob.glob("ACSST5Y20*.S1501-Data.csv"))

# Step 2: Filter ONLY 2010–2014
files = [f for f in files if re.search(r'201[0-4]', f)]

# Step 3: Create list to store dataframes
df_list = []

# Step 4: Loop through each file
for file in files:

    # Extract year from filename
    year = re.search(r'(\d{4})', file).group(1)

    # Read file
    df = pd.read_csv(file)

    # Add Year column
    df['Year'] = int(year)

    # Append to list
    df_list.append(df)

# Step 5: Stack all dataframes
edu_2010_2014 = pd.concat(df_list, ignore_index=True)

# Step 6: Save to Excel
edu_2010_2014.to_excel("ACS_Education_2010_2014.xlsx", index=False)

print("Done! Education dataset (2010–2014) saved 🎉")