# -*- coding: utf-8 -*-
"""Testing if there is a difference between counties that joined vs didn't join.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDxQ9_oJN8Sep1ObxMfJfSdD7fPQMgyc
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm

# Step 1: Load your data
df = pd.read_excel("/content/HOLY GRAIL MASS INFO DOC.xlsx")

df.columns

# Step 2: Define variables
Y = df["joined_or_not"]
X = df[["median_household_income"]]

# Step 3: Add constant (VERY IMPORTANT)
X = sm.add_constant(X)

# Step 4: Run regression
model = sm.OLS(Y, X).fit()

# Step 5: Print results
print(model.summary())



























