# -*- coding: utf-8 -*-
"""TRYING TO FIGURE STUFF OUT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1Icg5HRSqSYORl5BuBqEQf9I3wuYRj2
"""

# Step 1: Import pandas with lenient settings
import pandas as pd
import numpy as np

# Set pandas to be more forgiving
pd.set_option('future.no_silent_downcasting', True)

# Step 2: Define a flexible file loader function
def load_flexible(filepath):
    """Load Excel or CSV files with lenient settings"""
    try:
        if filepath.endswith(('.xlsx', '.xlsm', '.xls')):
            # Lenient Excel loading
            df = pd.read_excel(
                filepath,
                dtype=str,  # Load everything as string first to avoid type errors
                engine='openpyxl' if filepath.endswith(('.xlsx', '.xlsm')) else None,
                keep_default_na=False,  # Keep empty cells as empty string
                na_filter=False  # Don't auto-convert to NaN
            )
        else:
            # Lenient CSV loading
            df = pd.read_csv(
                filepath,
                dtype=str,
                keep_default_na=False,
                na_filter=False,
                encoding='utf-8',
                encoding_errors='ignore'
            )
        return df
    except Exception as e:
        print(f"⚠️ Warning: Could not load {filepath} - {e}")
        return None

# Step 3: Define file paths
files = {
    "elderly": "/content/Consolidated ACS % Elderly Cost Burdened Data.xlsm",
    "renter_owner": "/content/Consolidated ACS % renter vs owner.xlsm",
    "age": "/content/Consolidated ACS Age.xlsx",
    "education": "/content/Consolidated ACS Educational Attainment.xlsx",
    "home_value": "/content/Consolidated ACS Median Home Value.xlsx",
    "income": "/content/Consolidated ACS Median Household Income.xlsx",
    "racial": "/content/Consolidated ACS Racial Composition.xlsm",
    "rural_urban": "/content/rural_urban_expanded.xlsx",
    "census_all": "/content/CENSUS ALL COUNTIES.xlsm"
}

# Step 4: Clean and standardize function
def clean_fips_year(df, filename):
    """Clean FIPS (make 5-digit zero-padded) and Year (make integer)"""
    if df is None:
        return None

    # Find FIPS column (case-insensitive)
    fips_col = None
    for col in df.columns:
        if 'fips' in col.lower():
            fips_col = col
            break

    if fips_col:
        # Clean FIPS: remove decimals, ensure string, pad to 5 digits
        df[fips_col] = df[fips_col].astype(str).str.replace(r'\.0$', '', regex=True)
        df[fips_col] = df[fips_col].str.replace(r'\..*', '', regex=True)
        df[fips_col] = df[fips_col].str.zfill(5)
        df.rename(columns={fips_col: 'FIPS'}, inplace=True)
    else:
        print(f"⚠️ Warning: No FIPS column found in {filename}")

    # Find Year column (case-insensitive)
    year_col = None
    for col in df.columns:
        if 'year' in col.lower():
            year_col = col
            break

    if year_col:
        # Clean Year: extract first 4 digits, make integer
        df[year_col] = df[year_col].astype(str).str.extract(r'(\d{4})')[0]
        df[year_col] = pd.to_numeric(df[year_col], errors='coerce')
        df.rename(columns={year_col: 'Year'}, inplace=True)
    elif filename != "census_all":
        print(f"⚠️ Warning: No Year column found in {filename}")

    return df

def drop_identifier_columns(df, filename, keep_first_file=False):
    """Drop identifier columns (State_Name, County_Name, GEO_ID, etc.)"""
    if df is None:
        return None

    # List of identifier column patterns to drop
    identifier_patterns = ['county_name', 'state_name', 'geo_id', 'geoid',
                          'gisjoin', 'gis_join', 'name', 'county', 'state']

    cols_to_drop = []
    for col in df.columns:
        col_lower = col.lower()
        if col not in ['FIPS', 'Year']:
            # Check if this is an identifier column
            if any(pattern in col_lower for pattern in identifier_patterns):
                cols_to_drop.append(col)

    if cols_to_drop and not keep_first_file:
        print(f"   Dropping {len(cols_to_drop)} identifier columns from {filename}")
        df = df.drop(columns=cols_to_drop)
    elif cols_to_drop and keep_first_file:
        print(f"   Keeping identifier columns from {filename} (first file)")

    return df

# Step 5: Load first file (KEEP its identifier columns)
print("📂 Loading files...")
merged = load_flexible(files["elderly"])
if merged is None:
    raise Exception("Failed to load first file. Check file paths.")

merged = clean_fips_year(merged, "elderly")
merged = drop_identifier_columns(merged, "elderly", keep_first_file=True)  # Keep identifiers from first file

# Step 6: Merge all ACS + rural_urban files (DROP identifiers from subsequent files)
for key in ["renter_owner", "age", "education", "home_value", "income", "racial", "rural_urban"]:
    print(f"🔄 Merging: {key}")
    df_next = load_flexible(files[key])
    if df_next is not None:
        df_next = clean_fips_year(df_next, key)
        df_next = drop_identifier_columns(df_next, key, keep_first_file=False)  # Drop identifiers from other files

        # Convert all columns except FIPS and Year to numeric (coerce errors to NaN)
        for col in df_next.columns:
            if col not in ['FIPS', 'Year']:
                df_next[col] = pd.to_numeric(df_next[col], errors='coerce')

        # Merge (outer join to keep all data)
        merged = merged.merge(df_next, on=['FIPS', 'Year'], how='outer')
        print(f"   Merged shape: {merged.shape}")
    else:
        print(f"⚠️ Skipping {key} - failed to load")

# Step 7: Load and merge CENSUS ALL COUNTIES
print("\n📂 Loading CENSUS ALL COUNTIES...")
census = load_flexible(files["census_all"])
if census is not None:
    census = clean_fips_year(census, "census_all")

    # Find and clean join_year column
    join_year_col = None
    for col in census.columns:
        if 'join_year' in col.lower() or 'join year' in col.lower():
            join_year_col = col
            break

    if join_year_col:
        census['join_year'] = pd.to_numeric(census[join_year_col], errors='coerce')
        if join_year_col != 'join_year':
            census = census.drop(columns=[join_year_col])
    else:
        print("⚠️ Warning: No join_year column found in census file")
        census['join_year'] = np.nan

    # Keep only FIPS and join_year from census (to avoid overwriting any identifiers)
    census_clean = census[['FIPS', 'join_year']].copy()

    # Merge on FIPS only
    final = merged.merge(census_clean, on='FIPS', how='left')
else:
    print("❌ Failed to load census file")
    final = merged
    final['join_year'] = np.nan

# Step 8: Create NEW dynamic joined_or_not
print("\n📝 Creating dynamic joined_or_not column...")
final['joined_or_not'] = final.apply(
    lambda row: 1 if (pd.notna(row.get('join_year', np.nan)) and
                      pd.notna(row.get('Year', np.nan)) and
                      row['Year'] >= row['join_year'])
    else 0,
    axis=1
)

# Step 9: Convert all numeric columns (except FIPS and identifiers) to proper types
for col in final.columns:
    if col not in ['FIPS', 'Year', 'joined_or_not']:
        # Try to convert to numeric, but keep as is if fails
        try:
            final[col] = pd.to_numeric(final[col], errors='coerce')
        except:
            pass  # Keep as string if conversion fails

# Step 10: Save to Excel
output_path = "/content/all_data_merged_final.xlsx"
try:
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        final.to_excel(writer, sheet_name='All Data', index=False)
    print(f"\n✅ SUCCESS! File saved to: {output_path}")
except Exception as e:
    # Fallback to CSV if Excel fails
    output_path = "/content/all_data_merged_final.csv"
    final.to_csv(output_path, index=False)
    print(f"\n⚠️ Saved as CSV instead: {output_path}")

# Step 11: Show summary
print(f"\n📊 SUMMARY:")
print(f"Total rows: {len(final)}")
print(f"Total columns: {len(final.columns)}")

# Show first few rows
print(f"\nFirst 5 rows (first 10 columns):")
print(final.iloc[:5, :10])

# Show which identifier columns were kept
identifier_cols = [col for col in final.columns if any(x in col.lower() for x in
                   ['county', 'state', 'geo', 'name']) and col not in ['FIPS', 'Year']]
if identifier_cols:
    print(f"\n📌 Identifier columns kept from first file: {identifier_cols}")

# Step 12: Statistics on the new joined_or_not
print(f"\n📈 joined_or_not distribution:")
print(final['joined_or_not'].value_counts())
print(f"\n✅ Merge complete!")

# Step 1: Import pandas with lenient settings
import pandas as pd
import numpy as np

pd.set_option('future.no_silent_downcasting', True)

# Step 2: Define flexible file loader
def load_flexible(filepath):
    """Load Excel or CSV files with lenient settings"""
    try:
        if filepath.endswith(('.xlsx', '.xlsm', '.xls')):
            df = pd.read_excel(
                filepath,
                dtype=str,
                engine='openpyxl' if filepath.endswith(('.xlsx', '.xlsm')) else None,
                keep_default_na=False,
                na_filter=False
            )
        else:
            df = pd.read_csv(
                filepath,
                dtype=str,
                keep_default_na=False,
                na_filter=False,
                encoding='utf-8',
                encoding_errors='ignore'
            )
        return df
    except Exception as e:
        print(f"⚠️ Warning: Could not load {filepath} - {e}")
        return None

# Step 3: Define file paths
files = {
    "elderly": "/content/Consolidated ACS % Elderly Cost Burdened Data.xlsm",
    "renter_owner": "/content/Consolidated ACS % renter vs owner.xlsm",
    "age": "/content/Consolidated ACS Age.xlsx",
    "education": "/content/Consolidated ACS Educational Attainment.xlsx",
    "home_value": "/content/Consolidated ACS Median Home Value.xlsx",
    "income": "/content/Consolidated ACS Median Household Income.xlsx",
    "racial": "/content/Consolidated ACS Racial Composition.xlsm",
    "rural_urban": "/content/rural_urban_expanded.xlsx",
    "census_all": "/content/CENSUS ALL COUNTIES.xlsm"
}

# Step 4: Function to clean FIPS and Year
def clean_fips_year(df, filename):
    """Clean FIPS and Year columns"""
    if df is None:
        return None

    # Find FIPS column
    fips_col = None
    for col in df.columns:
        if 'fips' in col.lower():
            fips_col = col
            break

    if fips_col:
        df[fips_col] = df[fips_col].astype(str).str.replace(r'\.0$', '', regex=True)
        df[fips_col] = df[fips_col].str.replace(r'\..*', '', regex=True)
        df[fips_col] = df[fips_col].str.zfill(5)
        df.rename(columns={fips_col: 'FIPS'}, inplace=True)
    else:
        print(f"⚠️ Warning: No FIPS column found in {filename}")

    # Find Year column
    year_col = None
    for col in df.columns:
        if 'year' in col.lower():
            year_col = col
            break

    if year_col:
        df[year_col] = df[year_col].astype(str).str.extract(r'(\d{4})')[0]
        df[year_col] = pd.to_numeric(df[year_col], errors='coerce')
        df.rename(columns={year_col: 'Year'}, inplace=True)
    elif filename != "census_all":
        print(f"⚠️ Warning: No Year column found in {filename}")

    return df

# Step 5: Function to drop ALL identifier columns (for all files except first)
def drop_all_identifiers(df, filename, is_first_file=False):
    """Drop all identifier columns except FIPS and Year"""
    if df is None:
        return None

    if is_first_file:
        print(f"   Keeping all columns from first file: {filename}")
        return df

    # Columns to KEEP (only these)
    keep_columns = ['FIPS', 'Year']

    # Also keep any column that looks like data (not identifiers)
    # But drop common identifier columns
    cols_to_drop = []
    for col in df.columns:
        if col not in keep_columns:
            col_lower = col.lower()
            # Drop if it's a common identifier column
            if any(x in col_lower for x in ['state', 'county', 'geo_id', 'geoid', 'gisjoin', 'name']):
                cols_to_drop.append(col)

    if cols_to_drop:
        print(f"   Dropping {len(cols_to_drop)} identifier columns from {filename}: {cols_to_drop[:3]}...")
        df = df.drop(columns=cols_to_drop)

    return df

# Step 6: Load first file - KEEP ALL columns
print("📂 Loading first file...")
merged = load_flexible(files["elderly"])
if merged is None:
    raise Exception("Failed to load first file")

print(f"Original columns in first file: {merged.columns.tolist()}")
merged = clean_fips_year(merged, "elderly")
merged = drop_all_identifiers(merged, "elderly", is_first_file=True)
print(f"Columns after cleaning: {merged.columns.tolist()}")

# Step 7: Merge other files (dropping their identifiers)
for key in ["renter_owner", "age", "education", "home_value", "income", "racial", "rural_urban"]:
    print(f"\n🔄 Merging: {key}")
    df_next = load_flexible(files[key])
    if df_next is not None:
        df_next = clean_fips_year(df_next, key)
        df_next = drop_all_identifiers(df_next, key, is_first_file=False)

        # Convert data columns to numeric
        for col in df_next.columns:
            if col not in ['FIPS', 'Year']:
                df_next[col] = pd.to_numeric(df_next[col], errors='coerce')

        # Merge
        merged = merged.merge(df_next, on=['FIPS', 'Year'], how='outer')
        print(f"   Shape after merge: {merged.shape}")
    else:
        print(f"⚠️ Skipping {key}")

# Step 8: Load CENSUS file
print("\n📂 Loading CENSUS ALL COUNTIES...")
census = load_flexible(files["census_all"])
if census is not None:
    print(f"Census original columns: {census.columns.tolist()}")

    # Clean FIPS in census
    fips_col = None
    for col in census.columns:
        if 'fips' in col.lower():
            fips_col = col
            break

    if fips_col:
        census[fips_col] = census[fips_col].astype(str).str.replace(r'\.0$', '', regex=True)
        census[fips_col] = census[fips_col].str.replace(r'\..*', '', regex=True)
        census[fips_col] = census[fips_col].str.zfill(5)
        census.rename(columns={fips_col: 'FIPS'}, inplace=True)

    # Find join_year column
    join_year_col = None
    for col in census.columns:
        if 'join_year' in col.lower() or 'join year' in col.lower():
            join_year_col = col
            break

    if join_year_col:
        census['join_year'] = pd.to_numeric(census[join_year_col], errors='coerce')
        print(f"   Found join_year column - sample: {census['join_year'].head(5).tolist()}")
    else:
        print("   ⚠️ No join_year column found - checking available columns...")
        # Look for any column that might contain year info
        for col in census.columns:
            if 'year' in col.lower():
                print(f"   Found column with 'year': {col}")
        census['join_year'] = np.nan

    # Keep only FIPS and join_year from census
    if 'FIPS' in census.columns:
        census_clean = census[['FIPS', 'join_year']].copy()

        # DEBUG: Check FIPS matching
        print(f"\n🔍 Checking FIPS matches:")
        print(f"   Merged FIPS sample: {merged['FIPS'].dropna().unique()[:5].tolist()}")
        print(f"   Census FIPS sample: {census['FIPS'].dropna().unique()[:5].tolist()}")

        # Merge
        final = merged.merge(census_clean, on='FIPS', how='left')
        print(f"   Shape after census merge: {final.shape}")

        # Check join_year after merge
        print(f"   join_year non-null count: {final['join_year'].notna().sum()}")
    else:
        print("   ❌ No FIPS column in census file after cleaning!")
        final = merged
        final['join_year'] = np.nan
else:
    print("❌ Failed to load census file")
    final = merged
    final['join_year'] = np.nan

# Step 9: Create dynamic joined_or_not
print("\n📝 Creating dynamic joined_or_not column...")
final['joined_or_not'] = final.apply(
    lambda row: 1 if (pd.notna(row.get('join_year', np.nan)) and
                      pd.notna(row.get('Year', np.nan)) and
                      row['Year'] >= row['join_year'])
    else 0,
    axis=1
)

# Step 10: Check State_Name
if 'State_Name' in final.columns:
    blank_states = final['State_Name'].isna().sum()
    print(f"\n📌 State_Name column has {blank_states} blank rows out of {len(final)}")
    if blank_states > 0:
        print("   Sample of blank State_Name rows:")
        print(final[final['State_Name'].isna()][['FIPS', 'State_Name']].head(10))
else:
    print("\n📌 No State_Name column found in final dataset")
    # Check for any state-related columns
    state_cols = [col for col in final.columns if 'state' in col.lower()]
    if state_cols:
        print(f"   But found these state-related columns: {state_cols}")

# Step 11: Save to Excel
output_path = "/content/all_data_merged_final.xlsx"
try:
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        final.to_excel(writer, sheet_name='All Data', index=False)
    print(f"\n✅ SUCCESS! File saved to: {output_path}")
except Exception as e:
    output_path = "/content/all_data_merged_final.csv"
    final.to_csv(output_path, index=False)
    print(f"\n⚠️ Saved as CSV instead: {output_path}")

# Step 12: Final summary
print(f"\n📊 FINAL SUMMARY:")
print(f"Total rows: {len(final)}")
print(f"Total columns: {len(final.columns)}")
print(f"\n📈 joined_or_not distribution:")
print(final['joined_or_not'].value_counts())
print(f"\n📈 join_year stats:")
print(f"   Non-null: {final['join_year'].notna().sum()}")
print(f"   Unique values: {final['join_year'].dropna().unique()[:10].tolist() if final['join_year'].notna().any() else 'None'}")

print(f"\n✅ Merge complete! Check the file for State_Name and joined_or_not columns.")

# Step 1: Import pandas with lenient settings
import pandas as pd
import numpy as np

pd.set_option('future.no_silent_downcasting', True)

# Step 2: Define flexible file loader
def load_flexible(filepath):
    """Load Excel or CSV files with lenient settings"""
    try:
        if filepath.endswith(('.xlsx', '.xlsm', '.xls')):
            df = pd.read_excel(
                filepath,
                dtype=str,
                engine='openpyxl' if filepath.endswith(('.xlsx', '.xlsm')) else None,
                keep_default_na=False,
                na_filter=False
            )
        else:
            df = pd.read_csv(
                filepath,
                dtype=str,
                keep_default_na=False,
                na_filter=False,
                encoding='utf-8',
                encoding_errors='ignore'
            )
        return df
    except Exception as e:
        print(f"⚠️ Warning: Could not load {filepath} - {e}")
        return None

# Step 3: Define file paths
files = {
    "elderly": "/content/Consolidated ACS % Elderly Cost Burdened Data.xlsm",
    "renter_owner": "/content/Consolidated ACS % renter vs owner.xlsm",
    "age": "/content/Consolidated ACS Age.xlsx",
    "education": "/content/Consolidated ACS Educational Attainment.xlsx",
    "home_value": "/content/Consolidated ACS Median Home Value.xlsx",
    "income": "/content/Consolidated ACS Median Household Income.xlsx",
    "racial": "/content/Consolidated ACS Racial Composition.xlsm",
    "rural_urban": "/content/rural_urban_expanded.xlsx",
    "census_all": "/content/CENSUS ALL COUNTIES.xlsm"
}

# Step 4: Function to clean FIPS and Year
def clean_fips_year(df, filename, is_census=False):
    """Clean FIPS and Year columns"""
    if df is None:
        return None

    # Find FIPS column
    fips_col = None
    for col in df.columns:
        if 'fips' in col.lower():
            fips_col = col
            break

    if fips_col:
        # Clean FIPS: remove decimals, ensure string, pad to 5 digits
        df[fips_col] = df[fips_col].astype(str).str.replace(r'\.0$', '', regex=True)
        df[fips_col] = df[fips_col].str.replace(r'\..*', '', regex=True)
        df[fips_col] = df[fips_col].str.zfill(5)
        df.rename(columns={fips_col: 'FIPS'}, inplace=True)
    else:
        print(f"⚠️ Warning: No FIPS column found in {filename}")

    # For census, also check if there's a combined FIPS column
    if is_census and 'FIPS' not in df.columns:
        # Try to combine State FIPS and County FIPS
        state_fips = None
        county_fips = None
        for col in df.columns:
            if 'state fips' in col.lower():
                state_fips = col
            if 'county fips' in col.lower():
                county_fips = col

        if state_fips and county_fips:
            print(f"   Creating FIPS from State FIPS + County FIPS")
            df[state_fips] = df[state_fips].astype(str).str.zfill(2)
            df[county_fips] = df[county_fips].astype(str).str.zfill(3)
            df['FIPS'] = df[state_fips] + df[county_fips]

    # Find Year column (for non-census files)
    if not is_census:
        year_col = None
        for col in df.columns:
            if 'year' in col.lower():
                year_col = col
                break

        if year_col:
            df[year_col] = df[year_col].astype(str).str.extract(r'(\d{4})')[0]
            df[year_col] = pd.to_numeric(df[year_col], errors='coerce')
            df.rename(columns={year_col: 'Year'}, inplace=True)
        elif filename != "census_all":
            print(f"⚠️ Warning: No Year column found in {filename}")

    return df

# Step 5: Function to drop identifier columns
def drop_all_identifiers(df, filename, is_first_file=False):
    """Drop all identifier columns except FIPS and Year"""
    if df is None:
        return None

    if is_first_file:
        print(f"   Keeping all columns from first file: {filename}")
        return df

    # Columns to KEEP (only these)
    keep_columns = ['FIPS', 'Year']

    # Drop common identifier columns
    cols_to_drop = []
    for col in df.columns:
        if col not in keep_columns:
            col_lower = col.lower()
            if any(x in col_lower for x in ['state', 'county', 'geo_id', 'geoid', 'gisjoin', 'name', 'area name']):
                cols_to_drop.append(col)

    if cols_to_drop:
        print(f"   Dropping {len(cols_to_drop)} identifier columns from {filename}")
        df = df.drop(columns=cols_to_drop)

    return df

# Step 6: Load first file - KEEP ALL columns
print("📂 Loading first file...")
merged = load_flexible(files["elderly"])
if merged is None:
    raise Exception("Failed to load first file")

merged = clean_fips_year(merged, "elderly", is_census=False)
merged = drop_all_identifiers(merged, "elderly", is_first_file=True)

# Step 7: Merge other files
for key in ["renter_owner", "age", "education", "home_value", "income", "racial", "rural_urban"]:
    print(f"\n🔄 Merging: {key}")
    df_next = load_flexible(files[key])
    if df_next is not None:
        df_next = clean_fips_year(df_next, key, is_census=False)
        df_next = drop_all_identifiers(df_next, key, is_first_file=False)

        # Convert data columns to numeric
        for col in df_next.columns:
            if col not in ['FIPS', 'Year']:
                df_next[col] = pd.to_numeric(df_next[col], errors='coerce')

        merged = merged.merge(df_next, on=['FIPS', 'Year'], how='outer')
        print(f"   Shape after merge: {merged.shape}")

# Step 8: Load and fix CENSUS file
print("\n📂 Loading CENSUS ALL COUNTIES...")
census = load_flexible(files["census_all"])
if census is not None:
    print(f"Census original columns: {census.columns.tolist()}")

    # Clean census with special handling for FIPS
    census = clean_fips_year(census, "census_all", is_census=True)

    # Find join_year column
    join_year_col = None
    for col in census.columns:
        if 'join_year' in col.lower() or 'join year' in col.lower():
            join_year_col = col
            break

    if join_year_col:
        census['join_year'] = pd.to_numeric(census[join_year_col], errors='coerce')
        print(f"   Found join_year column - range: {census['join_year'].min()} to {census['join_year'].max()}")
    else:
        print("   ⚠️ No join_year column found!")
        census['join_year'] = np.nan

    # Check if we have FIPS now
    if 'FIPS' in census.columns:
        print(f"   Census FIPS sample: {census['FIPS'].dropna().unique()[:10].tolist()}")

        # Keep only FIPS and join_year
        census_clean = census[['FIPS', 'join_year']].copy()

        # Merge with merged data
        final = merged.merge(census_clean, on='FIPS', how='left')

        # Check if we got any matches
        matches = final['join_year'].notna().sum()
        print(f"   ✅ Found {matches} matching rows with join_year data!")

        if matches == 0:
            print("\n   ⚠️ Still no matches! Let me try to fix FIPS format...")
            # Try alternative FIPS formats
            if 'FIPS ' in census.columns:  # Note the space!
                census['FIPS_clean'] = census['FIPS '].astype(str).str.zfill(5)
                census_clean = census[['FIPS_clean', 'join_year']].copy()
                census_clean.rename(columns={'FIPS_clean': 'FIPS'}, inplace=True)
                final = merged.merge(census_clean, on='FIPS', how='left')
                matches = final['join_year'].notna().sum()
                print(f"   After fix: {matches} matching rows")
    else:
        print("   ❌ No FIPS column in census after cleaning!")
        final = merged
        final['join_year'] = np.nan
else:
    print("❌ Failed to load census file")
    final = merged
    final['join_year'] = np.nan

# Step 9: Create dynamic joined_or_not
print("\n📝 Creating dynamic joined_or_not column...")
final['joined_or_not'] = final.apply(
    lambda row: 1 if (pd.notna(row.get('join_year', np.nan)) and
                      pd.notna(row.get('Year', np.nan)) and
                      row['Year'] >= row['join_year'])
    else 0,
    axis=1
)

# Step 10: Fill blank State_Name if possible (using FIPS)
if 'State_Name' in final.columns:
    blank_states = final['State_Name'].isna().sum()
    print(f"\n📌 State_Name column has {blank_states} blank rows")

    if blank_states > 0:
        # Create a simple FIPS-to-State mapping (first 2 digits)
        # You can expand this mapping
        fips_to_state = {
            '01': 'Alabama', '02': 'Alaska', '04': 'Arizona', '05': 'Arkansas',
            '06': 'California', '08': 'Colorado', '09': 'Connecticut', '10': 'Delaware',
            '11': 'District of Columbia', '12': 'Florida', '13': 'Georgia', '15': 'Hawaii',
            '16': 'Idaho', '17': 'Illinois', '18': 'Indiana', '19': 'Iowa', '20': 'Kansas',
            '21': 'Kentucky', '22': 'Louisiana', '23': 'Maine', '24': 'Maryland',
            '25': 'Massachusetts', '26': 'Michigan', '27': 'Minnesota', '28': 'Mississippi',
            '29': 'Missouri', '30': 'Montana', '31': 'Nebraska', '32': 'Nevada',
            '33': 'New Hampshire', '34': 'New Jersey', '35': 'New Mexico', '36': 'New York',
            '37': 'North Carolina', '38': 'North Dakota', '39': 'Ohio', '40': 'Oklahoma',
            '41': 'Oregon', '42': 'Pennsylvania', '44': 'Rhode Island', '45': 'South Carolina',
            '46': 'South Dakota', '47': 'Tennessee', '48': 'Texas', '49': 'Utah',
            '50': 'Vermont', '51': 'Virginia', '53': 'Washington', '54': 'West Virginia',
            '55': 'Wisconsin', '56': 'Wyoming', '60': 'American Samoa', '66': 'Guam',
            '69': 'Northern Mariana Islands', '72': 'Puerto Rico', '78': 'Virgin Islands'
        }

        # Fill blank State_Name using FIPS first two digits
        final['State_FIPS_prefix'] = final['FIPS'].astype(str).str[:2]
        final['State_Name_Filled'] = final['State_FIPS_prefix'].map(fips_to_state)
        final['State_Name'] = final['State_Name'].fillna(final['State_Name_Filled'])

        new_blanks = final['State_Name'].isna().sum()
        print(f"   Filled {blank_states - new_blanks} blank State_Name rows using FIPS codes")
        final = final.drop(columns=['State_FIPS_prefix', 'State_Name_Filled'])

# Step 11: Save to Excel
output_path = "/content/all_data_merged_final.xlsx"
try:
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        final.to_excel(writer, sheet_name='All Data', index=False)
    print(f"\n✅ SUCCESS! File saved to: {output_path}")
except Exception as e:
    output_path = "/content/all_data_merged_final.csv"
    final.to_csv(output_path, index=False)
    print(f"\n⚠️ Saved as CSV instead: {output_path}")

# Step 12: Final summary
print(f"\n📊 FINAL SUMMARY:")
print(f"Total rows: {len(final)}")
print(f"Total columns: {len(final.columns)}")
print(f"\n📈 joined_or_not distribution:")
print(final['joined_or_not'].value_counts())
print(f"\n📈 Sample of joined data (first 10 rows with join_year):")
sample = final[final['join_year'].notna()].head(10)
if len(sample) > 0:
    print(sample[['FIPS', 'Year', 'join_year', 'joined_or_not', 'State_Name']])
else:
    print("   No matching join_year data found - check FIPS codes")

print(f"\n✅ Merge complete!")

# Final verification and summary
print("=" * 60)
print("FINAL DATA VERIFICATION")
print("=" * 60)

# 1. Check join_year distribution
print("\n📅 join_year distribution (when counties joined):")
print(final['join_year'].value_counts().sort_index().head(10))

# 2. Check counties that HAVE joined (joined_or_not = 1)
joined_counties = final[final['joined_or_not'] == 1]['FIPS'].unique()
print(f"\n✅ Counties that have joined (at least one year with joined_or_not=1): {len(joined_counties)} counties")

# 3. Show example of a county that joined
if len(joined_counties) > 0:
    example_fips = joined_counties[0]
    print(f"\n📊 Example county FIPS {example_fips}:")
    example_data = final[final['FIPS'] == example_fips][['FIPS', 'Year', 'join_year', 'joined_or_not', 'State_Name']]
    print(example_data.head(15))

    # Show when they joined
    join_yr = example_data['join_year'].iloc[0]
    print(f"\n   This county joined in {join_yr}")
    print(f"   Years before {join_yr}: joined_or_not = 0")
    print(f"   Years {join_yr} and after: joined_or_not = 1")

# 4. Check for any data issues
print("\n🔍 Data quality checks:")
print(f"   Total rows: {len(final)}")
print(f"   Total counties: {final['FIPS'].nunique()}")
print(f"   Year range: {final['Year'].min()} to {final['Year'].max()}")
print(f"   join_year range: {final['join_year'].min()} to {final['join_year'].max()}")

# 5. Show counties with missing State_Name (should be 0 now)
missing_state = final['State_Name'].isna().sum()
print(f"   Missing State_Name: {missing_state} rows")

# 6. Verify joined_or_not logic with a few random samples
print("\n📋 Verifying joined_or_not logic (random samples):")
sample_rows = final[final['join_year'].notna()].sample(min(5, len(final[final['join_year'].notna()])))
for idx, row in sample_rows.iterrows():
    expected = 1 if row['Year'] >= row['join_year'] else 0
    status = "✅" if row['joined_or_not'] == expected else "❌"
    print(f"   {status} FIPS {row['FIPS']}: Year={row['Year']}, join_year={row['join_year']}, joined_or_not={row['joined_or_not']} (expected {expected})")

# 7. Summary statistics for joined counties over time
print("\n📈 Counties joining by year:")
joining_by_year = final[final['join_year'].notna()].groupby('join_year')['FIPS'].nunique()
print(joining_by_year)

# 8. Save a separate sheet with just the joined_or_not logic for verification
verification_output = "/content/joined_verification.xlsx"
with pd.ExcelWriter(verification_output, engine='openpyxl') as writer:
    # Main data
    final.to_excel(writer, sheet_name='All Data', index=False)

    # Just the key columns for verification
    final[['FIPS', 'Year', 'join_year', 'joined_or_not', 'State_Name']].to_excel(
        writer, sheet_name='Join_Logic_Check', index=False
    )

    # Counties that have joined
    joined_summary = final[final['joined_or_not'] == 1].groupby(['FIPS', 'State_Name', 'join_year'])['Year'].agg(['min', 'max', 'count'])
    joined_summary.to_excel(writer, sheet_name='Counties_That_Joined')

print(f"\n✅ Verification file saved to: {verification_output}")

print("\n" + "=" * 60)
print("✅ ALL DONE! Your data is ready for analysis.")
print("=" * 60)
print("\n📌 Key takeaways:")
print("   1. joined_or_not = 1 means Year >= join_year")
print("   2. joined_or_not = 0 means Year < join_year or no join_year data")
print("   3. State_Name has been filled for all rows using FIPS codes")
print("   4. Total of 1,080 rows have joined_or_not = 1")
print("\n💡 For analysis, you can now:")
print("   - Filter to joined_or_not == 1 to study post-join periods")
print("   - Compare pre-join (0) vs post-join (1) within counties")
print("   - Use join_year as a fixed effect in models")

# Step 1: Import pandas
import pandas as pd
import numpy as np

# Step 2: Define flexible file loader
def load_flexible(filepath):
    """Load Excel files with lenient settings"""
    try:
        if filepath.endswith(('.xlsx', '.xlsm', '.xls')):
            df = pd.read_excel(
                filepath,
                dtype=str,  # Load everything as string first
                engine='openpyxl' if filepath.endswith(('.xlsx', '.xlsm')) else None,
                keep_default_na=False,
                na_filter=False
            )
        else:
            df = pd.read_csv(
                filepath,
                dtype=str,
                keep_default_na=False,
                na_filter=False,
                encoding='utf-8',
                encoding_errors='ignore'
            )
        return df
    except Exception as e:
        print(f"⚠️ Warning: Could not load {filepath} - {e}")
        return None

# Step 3: Define file paths for ACS + rural_urban files ONLY
files = {
    "elderly": "/content/Consolidated ACS % Elderly Cost Burdened Data.xlsm",
    "renter_owner": "/content/Consolidated ACS % renter vs owner.xlsm",
    "age": "/content/Consolidated ACS Age.xlsx",
    "education": "/content/Consolidated ACS Educational Attainment.xlsx",
    "home_value": "/content/Consolidated ACS Median Home Value.xlsx",
    "income": "/content/Consolidated ACS Median Household Income.xlsx",
    "racial": "/content/Consolidated ACS Racial Composition.xlsm",
    "rural_urban": "/content/rural_urban_expanded.xlsx"
}

# Step 4: Function to clean FIPS and Year
def clean_fips_year(df, filename):
    """Clean FIPS (5-digit) and Year (integer)"""
    if df is None:
        return None

    # Find and clean FIPS column
    fips_col = None
    for col in df.columns:
        if 'fips' in col.lower():
            fips_col = col
            break

    if fips_col:
        # Clean FIPS: remove decimals, ensure string, pad to 5 digits
        df[fips_col] = df[fips_col].astype(str).str.replace(r'\.0$', '', regex=True)
        df[fips_col] = df[fips_col].str.replace(r'\..*', '', regex=True)
        df[fips_col] = df[fips_col].str.zfill(5)
        df.rename(columns={fips_col: 'FIPS'}, inplace=True)
    else:
        print(f"⚠️ Warning: No FIPS column found in {filename}")
        return None

    # Find and clean Year column
    year_col = None
    for col in df.columns:
        if 'year' in col.lower():
            year_col = col
            break

    if year_col:
        # Clean Year: extract first 4 digits, make integer
        df[year_col] = df[year_col].astype(str).str.extract(r'(\d{4})')[0]
        df[year_col] = pd.to_numeric(df[year_col], errors='coerce')
        df.rename(columns={year_col: 'Year'}, inplace=True)
    else:
        print(f"⚠️ Warning: No Year column found in {filename}")
        return None

    return df

# Step 5: Keep only essential columns from each file
def keep_data_columns(df, filename, keep_identifiers=True):
    """Keep FIPS, Year, and data columns (drop duplicate identifiers)"""
    if df is None:
        return None

    # Always keep FIPS and Year
    keep_cols = ['FIPS', 'Year']

    # For first file, keep identifier columns
    if keep_identifiers:
        for col in df.columns:
            if col not in keep_cols:
                # Keep everything from first file
                keep_cols.append(col)
    else:
        # For other files, only keep columns that look like data (not identifiers)
        for col in df.columns:
            if col not in keep_cols:
                col_lower = col.lower()
                # Keep if it's NOT an identifier column
                if not any(x in col_lower for x in ['state', 'county', 'geo_id', 'geoid', 'name']):
                    keep_cols.append(col)

    return df[keep_cols]

# Step 6: Load and clean first file (keep all its columns)
print("📂 Loading first file (Elderly Cost Burdened)...")
merged = load_flexible(files["elderly"])
merged = clean_fips_year(merged, "elderly")
merged = keep_data_columns(merged, "elderly", keep_identifiers=True)
print(f"   Shape: {merged.shape}")
print(f"   Columns: {merged.columns.tolist()[:10]}...")  # Show first 10 columns

# Step 7: Merge remaining files one by one
for key in ["renter_owner", "age", "education", "home_value", "income", "racial", "rural_urban"]:
    print(f"\n🔄 Merging: {key}")
    df_next = load_flexible(files[key])

    if df_next is not None:
        # Clean FIPS and Year
        df_next = clean_fips_year(df_next, key)

        if df_next is not None:
            # Keep only data columns (drop identifiers)
            df_next = keep_data_columns(df_next, key, keep_identifiers=False)

            # Convert all data columns to numeric
            for col in df_next.columns:
                if col not in ['FIPS', 'Year']:
                    df_next[col] = pd.to_numeric(df_next[col], errors='coerce')

            # Merge
            before_shape = merged.shape
            merged = merged.merge(df_next, on=['FIPS', 'Year'], how='outer')
            after_shape = merged.shape
            print(f"   Shape: {after_shape} (added {after_shape[1] - before_shape[1]} new columns)")
    else:
        print(f"   ⚠️ Failed to load {key}")

# Step 8: Final cleaning
print("\n🧹 Final cleaning...")

# Convert all columns (except FIPS, Year, and identifiers) to numeric
for col in merged.columns:
    if col not in ['FIPS', 'Year', 'County_Name', 'State_Name', 'GEO_ID']:
        merged[col] = pd.to_numeric(merged[col], errors='coerce')

# Sort by FIPS and Year
merged = merged.sort_values(['FIPS', 'Year']).reset_index(drop=True)

# Step 9: Save the merged file (NO CENSUS DATA)
output_path = "/content/acs_rural_merged_only.xlsx"
try:
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        merged.to_excel(writer, sheet_name='ACS_Rural_Data', index=False)
    print(f"\n✅ SUCCESS! File saved to: {output_path}")
except Exception as e:
    output_path = "/content/acs_rural_merged_only.csv"
    merged.to_csv(output_path, index=False)
    print(f"\n⚠️ Saved as CSV instead: {output_path}")

# Step 10: Summary
print("\n" + "=" * 60)
print("MERGE COMPLETE - NO CENSUS DATA")
print("=" * 60)
print(f"\n📊 Final dataset summary:")
print(f"   Total rows: {len(merged):,}")
print(f"   Total columns: {len(merged.columns)}")
print(f"   Years: {merged['Year'].min()} to {merged['Year'].max()}")
print(f"   Unique counties: {merged['FIPS'].nunique():,}")
print(f"\n📋 Column types:")
print(f"   Identifier columns: {[col for col in merged.columns if col in ['FIPS', 'Year', 'County_Name', 'State_Name', 'GEO_ID']]}")
data_cols = [col for col in merged.columns if col not in ['FIPS', 'Year', 'County_Name', 'State_Name', 'GEO_ID']]
print(f"   Data columns: {len(data_cols)} columns")
print(f"\n✅ First 5 rows (FIPS, Year, State_Name):")
print(merged[['FIPS', 'Year', 'State_Name']].head())

# Step 11: Download option
print(f"\n📥 To download, run:")
print(f"   from google.colab import files")
print(f"   files.download('{output_path}')")

# Step 1: Import pandas
import pandas as pd
import numpy as np

# Step 2: Load your already-merged ACS + rural_urban data (from your successful merge)
print("📂 Loading your merged ACS + rural_urban data...")
acs_data = pd.read_excel("/content/acs_rural_merged_only.xlsx")
print(f"   Shape: {acs_data.shape}")
print(f"   Years: {acs_data['Year'].min()} to {acs_data['Year'].max()}")
print(f"   Unique counties: {acs_data['FIPS'].nunique()}")

# Step 3: Load the CENSUS ALL COUNTIES file
print("\n📂 Loading CENSUS ALL COUNTIES...")
census = pd.read_excel("/content/CENSUS ALL COUNTIES.xlsm", dtype=str)
print(f"   Original shape: {census.shape}")
print(f"   Columns: {census.columns.tolist()}")

# Step 4: Clean the census file
print("\n🧹 Cleaning census file...")

# Create clean FIPS code (combine State FIPS + County FIPS if needed)
if 'FIPS ' in census.columns:  # Note the space!
    census['FIPS'] = census['FIPS '].astype(str).str.zfill(5)
elif 'State FIPS Code' in census.columns and 'County FIPS Code' in census.columns:
    census['State FIPS Code'] = census['State FIPS Code'].astype(str).str.zfill(2)
    census['County FIPS Code'] = census['County FIPS Code'].astype(str).str.zfill(3)
    census['FIPS'] = census['State FIPS Code'] + census['County FIPS Code']
else:
    # Try to find any FIPS column
    for col in census.columns:
        if 'fips' in col.lower():
            census['FIPS'] = census[col].astype(str).str.zfill(5)
            break

# Clean join_year
if 'join_year' in census.columns:
    census['join_year'] = pd.to_numeric(census['join_year'], errors='coerce')
else:
    # Try to find join_year column
    for col in census.columns:
        if 'join_year' in col.lower() or 'join year' in col.lower():
            census['join_year'] = pd.to_numeric(census[col], errors='coerce')
            break

# Keep only necessary columns from census
census_clean = census[['FIPS', 'join_year']].copy()
census_clean = census_clean.dropna(subset=['FIPS'])  # Remove rows without FIPS
print(f"   Cleaned census shape: {census_clean.shape}")
print(f"   Unique counties in census: {census_clean['FIPS'].nunique()}")
print(f"   Join year range: {census_clean['join_year'].min()} to {census_clean['join_year'].max()}")

# Step 5: EXPAND census to have all years (2010-2024)
print("\n📅 Expanding census to include all years 2010-2024...")

# Create all combinations of FIPS and Year
all_years = list(range(2010, 2025))  # 2010 to 2024 inclusive

# For each FIPS in census, repeat for every year
expanded_census = []
for fips in census_clean['FIPS'].unique():
    join_year = census_clean[census_clean['FIPS'] == fips]['join_year'].iloc[0]
    for year in all_years:
        expanded_census.append({
            'FIPS': fips,
            'Year': year,
            'join_year': join_year
        })

expanded_census = pd.DataFrame(expanded_census)
print(f"   Expanded census shape: {expanded_census.shape}")
print(f"   Expected: {census_clean['FIPS'].nunique()} counties × 15 years = {census_clean['FIPS'].nunique() * 15} rows")
print(f"   Actual: {len(expanded_census)} rows")

# Step 6: Merge expanded census with ACS data
print("\n🔄 Merging expanded census with ACS data...")
final = acs_data.merge(expanded_census, on=['FIPS', 'Year'], how='left')
print(f"   Final shape: {final.shape}")

# Step 7: Create dynamic joined_or_not
print("\n📝 Creating dynamic joined_or_not column...")
final['joined_or_not'] = final.apply(
    lambda row: 1 if (pd.notna(row['join_year']) and
                      pd.notna(row['Year']) and
                      row['Year'] >= row['join_year'])
    else 0,
    axis=1
)

# Step 8: Fill missing State_Name (if needed)
if 'State_Name' not in final.columns:
    # Try to find state name from FIPS if available
    print("\n📌 Adding State_Name from FIPS codes...")
    fips_to_state = {
        '01': 'Alabama', '02': 'Alaska', '04': 'Arizona', '05': 'Arkansas',
        '06': 'California', '08': 'Colorado', '09': 'Connecticut', '10': 'Delaware',
        '11': 'District of Columbia', '12': 'Florida', '13': 'Georgia', '15': 'Hawaii',
        '16': 'Idaho', '17': 'Illinois', '18': 'Indiana', '19': 'Iowa', '20': 'Kansas',
        '21': 'Kentucky', '22': 'Louisiana', '23': 'Maine', '24': 'Maryland',
        '25': 'Massachusetts', '26': 'Michigan', '27': 'Minnesota', '28': 'Mississippi',
        '29': 'Missouri', '30': 'Montana', '31': 'Nebraska', '32': 'Nevada',
        '33': 'New Hampshire', '34': 'New Jersey', '35': 'New Mexico', '36': 'New York',
        '37': 'North Carolina', '38': 'North Dakota', '39': 'Ohio', '40': 'Oklahoma',
        '41': 'Oregon', '42': 'Pennsylvania', '44': 'Rhode Island', '45': 'South Carolina',
        '46': 'South Dakota', '47': 'Tennessee', '48': 'Texas', '49': 'Utah',
        '50': 'Vermont', '51': 'Virginia', '53': 'Washington', '54': 'West Virginia',
        '55': 'Wisconsin', '56': 'Wyoming', '60': 'American Samoa', '66': 'Guam',
        '69': 'Northern Mariana Islands', '72': 'Puerto Rico', '78': 'Virgin Islands'
    }
    final['State_FIPS_prefix'] = final['FIPS'].astype(str).str[:2]
    final['State_Name'] = final['State_FIPS_prefix'].map(fips_to_state)
    final = final.drop(columns=['State_FIPS_prefix'])

# Step 9: Verify the merge
print("\n" + "=" * 60)
print("VERIFICATION")
print("=" * 60)

# Check join_year distribution
print("\n📅 join_year distribution:")
print(final['join_year'].value_counts().sort_index().head(15))

# Check joined_or_not
print(f"\n📈 joined_or_not distribution:")
print(final['joined_or_not'].value_counts())

# Show example county
example_fips = final[final['joined_or_not'] == 1]['FIPS'].iloc[0] if len(final[final['joined_or_not'] == 1]) > 0 else final['FIPS'].iloc[0]
print(f"\n📊 Example county FIPS {example_fips}:")
example = final[final['FIPS'] == example_fips][['FIPS', 'Year', 'join_year', 'joined_or_not', 'State_Name']].head(15)
print(example)

# Step 10: Save final file
output_path = "/content/final_complete_merge.xlsx"
try:
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        final.to_excel(writer, sheet_name='All_Data', index=False)
    print(f"\n✅ SUCCESS! File saved to: {output_path}")
except Exception as e:
    output_path = "/content/final_complete_merge.csv"
    final.to_csv(output_path, index=False)
    print(f"\n⚠️ Saved as CSV instead: {output_path}")

# Step 11: Final summary
print("\n" + "=" * 60)
print("FINAL SUMMARY")
print("=" * 60)
print(f"\n📊 Dataset stats:")
print(f"   Total rows: {len(final):,}")
print(f"   Total columns: {len(final.columns)}")
print(f"   Years: {final['Year'].min()} to {final['Year'].max()}")
print(f"   Unique counties: {final['FIPS'].nunique():,}")
print(f"\n📈 joined_or_not:")
print(f"   Counties that joined: {final[final['joined_or_not'] == 1]['FIPS'].nunique()}")
print(f"   Rows with joined_or_not = 1: {final['joined_or_not'].sum():,}")
print(f"   Rows with joined_or_not = 0: {(final['joined_or_not'] == 0).sum():,}")

print(f"\n✅ Perfect! Now every county appears for all years 2010-2024")
print(f"\n📥 To download, run:")
print(f"   from google.colab import files")
print(f"   files.download('{output_path}')")

# Optional: Download immediately
from google.colab import files
files.download(output_path)